# Generated by Django 4.2.7 on 2024-05-07 13:25

from django.db import migrations, models
import short_url.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=400)),
                (
                    "code",
                    models.CharField(
                        default=short_url.utils.generate_url_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
